In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 50)

# Merging with AME

In [3]:
masses = pd.read_csv("./Element_Properties/Final_Element_Properties.csv")

In [4]:
masses = masses.rename(columns={'N': 'Neutrons', 'A': 'Mass_Number', 'Neutrons':'N', 'Mass_Number':'M'})

In [5]:
masses.head()

,Neutrons,Z,O,Mass_Excess,dMass_Excess,Binding_Energy,dBinding_Energy,B_Decay_Energy,dB_Decay_Energy,Atomic_Mass_Micro,dAtomic_Mass_Micro,S(2n),dS(2n),S(2p),dS(2p),Q(a),dQ(a),Q(2B-),dQ(2B-),Q(ep),dQ(ep),Q(B-n),dQ(B-n),Mass_Number,EL,S(n),dS(n),S(p),dS(p),Q(4B-),dQ(4B-),"Q(d,a)","dQ(d,a)","Q(p,a)","dQ(p,a)","Q(n,a)","dQ(n,a)","Q(g,p)","Q(g,n)","Q(g,pn)","Q(g,d)","Q(g,t)","Q(g,He3)","Q(g,2p)","Q(g,2n)","Q(g,a)","Q(p,n)","Q(p,2p)","Q(p,pn)","Q(p,d)","Q(p,2n)","Q(p,t)","Q(p,3He)","Q(n,2p)","Q(n,np)","Q(n,d)","Q(n,2n)","Q(n,t)","Q(n,3He)","Q(d,t)","Q(d,3He)","Q(3He,t)","Q(3He,a)","Q(t,a)",N,M
0,1,0,Other,8071.31713,0.00046,0.000,0.0,782.347,0.0000,1.008665e+06,0.00049,0.000,0.000,0.00,0.0,0.0,0.0,0.000,0.000000,0.0,0.0,0.000000,0.000000,1,n,0.000000,0.000000,0.000,0.0,0.00,0.000000,0.000,0.0,0.000000,0.000000,0.00,0.0,0.000,-0.000000,0.0000,0.0000,0.000000,0.0000,0.00,0.000,0.0,0.0005,0.000,-0.000000,2224.566000,0.000000,0.0000,0.0000,0.0,0.000,0.000,-0.000000,0.0000,0.0000,6257.229000,0.0000,763.755,20577.619400,0.0000,1,1
1,0,1,Other,7288.97061,0.00009,0.000,0.0,18244.328,289.9558,1.007825e+06,0.00009,2025.412,292.506,0.00,0.0,0.0,0.0,13762.268,719.024000,0.0,0.0,17514.992500,362.087500,1,H,1096.973333,256.595000,0.000,0.0,8007.50,1511.500000,20717.915,0.0,20613.860000,50.000000,0.00,0.0,-0.000,-1096.973333,-5353.1789,-3128.6129,799.995100,0.0000,0.00,-2025.412,0.0,17461.9815,-0.000,-1096.973333,1127.592667,16732.646000,6456.3829,2364.8615,0.0,-0.000,2224.566,-1096.973333,3128.6161,0.0000,5160.255667,5493.4744,18225.736,19480.646067,19813.8649,0,1
2,1,1,Other,13135.72176,0.00011,1112.283,0.0,18244.328,289.9558,2.014102e+06,0.00012,2025.412,292.506,0.00,0.0,0.0,0.0,13762.268,719.024000,0.0,0.0,17514.992500,362.087500,2,H,2224.570000,0.000000,2224.570,0.0,8007.50,1511.500000,23846.530,0.0,20613.860000,50.000000,0.00,0.0,-2224.570,-2224.570000,-2224.5639,0.0021,799.995100,0.0000,0.00,-2025.412,0.0,17461.9815,-2224.570,-2224.570000,-0.004000,16732.646000,6456.3829,5493.4765,0.0,-2224.570,-0.004,-2224.570000,6257.2311,0.0000,4032.659000,3268.9044,18225.736,18353.049400,17589.2949,1,2
3,2,1,Other,14949.80993,0.00022,2827.265,0.0,18.592,0.0000,3.016049e+06,0.00023,8481.790,0.000,0.00,0.0,0.0,0.0,-13717.000,2000.000000,0.0,0.0,17514.992500,362.087500,3,H,6257.230000,0.000000,1112.285,0.0,8007.50,1511.500000,17589.300,0.0,19813.860000,0.000000,0.00,0.0,-1112.285,-6257.230000,-8481.7939,-6257.2279,-0.004900,0.0000,0.00,-8481.790,0.0,-763.7545,-1112.285,-6257.230000,-4032.664000,16732.646000,0.0049,-763.7535,0.0,-1112.285,1112.281,-6257.230000,0.0011,0.0000,-0.001000,4381.1894,0.000,14320.389400,18701.5799,2,3
4,1,2,Other,14931.21793,0.00021,2572.680,0.0,-13736.000,2000.0000,3.016029e+06,0.00022,4013.160,30.300,7718.04,0.0,367.5,10.0,12743.205,359.296667,0.0,0.0,-2571.224286,344.341429,3,He,3176.184286,29.417143,5493.470,0.0,14022.91,52.653333,18353.050,0.0,4173.344286,210.882857,20577.62,0.0,-5493.470,-3176.184286,-7718.0439,-5493.4779,-15640.520614,0.0006,-7718.04,-4013.160,367.5,-14518.3465,-5493.470,-3176.184286,-951.618286,-3353.570786,4468.6349,-0.0035,0.0,-5493.470,-3268.904,-3176.184286,763.7511,0.0004,3081.044714,0.0044,-13754.592,17401.435114,14320.3949,1,3

In [6]:
df = pd.read_csv("working_xs.csv")

C:\Users\Pedro\Anaconda3\envs\data_mining_2\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [7]:
df.head()

,Prj,Target_Meta_State,MF,MT,Energy,dEnergy,Data,dData,Cos/LO,dCos/LO,ELV/HL,dELV/HL,I78,Refer,Z,M,N,Product_Meta_State,Frame,Type,Title,Year,Date,Institute,Reaction,Out
0,1,G,3,1,88200000.0,882000.0,0.0300,0.001523,NaN,NaN,NaN,NaN,L,"D.F.MEASDAY,ET.AL. (66)",0,1,1,G,L,"0-NN-1(N,TOT),,SIG","NEUTRON TOTAL CROSS SECTIONS FOR NEUTRONS, PRO...",1966,19800804,(1USAHRV),"N,TOT",TOT
1,1,G,3,1,98100000.0,981000.0,0.0291,0.001516,NaN,NaN,NaN,NaN,L,"D.F.MEASDAY,ET.AL. (66)",0,1,1,G,L,"0-NN-1(N,TOT),,SIG","NEUTRON TOTAL CROSS SECTIONS FOR NEUTRONS, PRO...",1966,19800804,(1USAHRV),"N,TOT",TOT
2,1,G,3,1,110000000.0,1100000.0,0.0279,0.001415,NaN,NaN,NaN,NaN,L,"D.F.MEASDAY,ET.AL. (66)",0,1,1,G,L,"0-NN-1(N,TOT),,SIG","NEUTRON TOTAL CROSS SECTIONS FOR NEUTRONS, PRO...",1966,19800804,(1USAHRV),"N,TOT",TOT
3,1,G,3,1,119600000.0,1196000.0,0.0264,0.001403,NaN,NaN,NaN,NaN,L,"D.F.MEASDAY,ET.AL. (66)",0,1,1,G,L,"0-NN-1(N,TOT),,SIG","NEUTRON TOTAL CROSS SECTIONS FOR NEUTRONS, PRO...",1966,19800804,(1USAHRV),"N,TOT",TOT
4,1,G,3,1,129400000.0,1294000.0,0.0256,0.001397,NaN,NaN,NaN,NaN,L,"D.F.MEASDAY,ET.AL. (66)",0,1,1,G,L,"0-NN-1(N,TOT),,SIG","NEUTRON TOTAL CROSS SECTIONS FOR NEUTRONS, PRO...",1966,19800804,(1USAHRV),"N,TOT",TOT

In [8]:
df = df.reset_index(drop=True)
masses = masses.reset_index(drop=True)

In [9]:
df = df.merge(masses, on=['N', 'Z'], how='left')

# Neutron Induced Cross Section vs Energy Data 

MF are ENDF labels and are used to store different types of data:

- MF=1 contains descriptive and miscellaneous data,
- MF=2 contains resonance parameter data,
- MF=3 contains reaction cross sections vs energy,
- MF=4 contains angular distributions,
- MF=5 contains energy distributions,
- MF=6 contains energy-angle distributions,
- MF=7 contains thermal scattering data,
- MF=8 contains radioactivity data
- MF=9-10 contain nuclide production data,
- MF=12-15 contain photon production data, and
- MF=30-36 contain covariance data.

In [10]:
df = df[df["MF"] == 3]
df =  df[~(df["MT"] > 999)] # Cross Section Ratios

In [11]:
df.head()

,Prj,Target_Meta_State,MF,MT,Energy,dEnergy,Data,dData,Cos/LO,dCos/LO,ELV/HL,dELV/HL,I78,Refer,Z,M_x,N,Product_Meta_State,Frame,Type,Title,Year,Date,Institute,Reaction,Out,Neutrons,O,Mass_Excess,dMass_Excess,Binding_Energy,dBinding_Energy,B_Decay_Energy,dB_Decay_Energy,Atomic_Mass_Micro,dAtomic_Mass_Micro,S(2n),dS(2n),S(2p),dS(2p),Q(a),dQ(a),Q(2B-),dQ(2B-),Q(ep),dQ(ep),Q(B-n),dQ(B-n),Mass_Number,EL,S(n),dS(n),S(p),dS(p),Q(4B-),dQ(4B-),"Q(d,a)","dQ(d,a)","Q(p,a)","dQ(p,a)","Q(n,a)","dQ(n,a)","Q(g,p)","Q(g,n)","Q(g,pn)","Q(g,d)","Q(g,t)","Q(g,He3)","Q(g,2p)","Q(g,2n)","Q(g,a)","Q(p,n)","Q(p,2p)","Q(p,pn)","Q(p,d)","Q(p,2n)","Q(p,t)","Q(p,3He)","Q(n,2p)","Q(n,np)","Q(n,d)","Q(n,2n)","Q(n,t)","Q(n,3He)","Q(d,t)","Q(d,3He)","Q(3He,t)","Q(3He,a)","Q(t,a)",M_y
0,1,G,3,1,88200000.0,882000.0,0.0300,0.001523,NaN,NaN,NaN,NaN,L,"D.F.MEASDAY,ET.AL. (66)",0,1,1,G,L,"0-NN-1(N,TOT),,SIG","NEUTRON TOTAL CROSS SECTIONS FOR NEUTRONS, PRO...",1966,19800804,(1USAHRV),"N,TOT",TOT,1.0,Other,8071.31713,0.00046,0.0,0.0,782.347,0.0,1.008665e+06,0.00049,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0005,0.0,-0.0,2224.566,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,6257.229,0.0,763.755,20577.6194,0.0,1.0
1,1,G,3,1,98100000.0,981000.0,0.0291,0.001516,NaN,NaN,NaN,NaN,L,"D.F.MEASDAY,ET.AL. (66)",0,1,1,G,L,"0-NN-1(N,TOT),,SIG","NEUTRON TOTAL CROSS SECTIONS FOR NEUTRONS, PRO...",1966,19800804,(1USAHRV),"N,TOT",TOT,1.0,Other,8071.31713,0.00046,0.0,0.0,782.347,0.0,1.008665e+06,0.00049,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0005,0.0,-0.0,2224.566,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,6257.229,0.0,763.755,20577.6194,0.0,1.0
2,1,G,3,1,110000000.0,1100000.0,0.0279,0.001415,NaN,NaN,NaN,NaN,L,"D.F.MEASDAY,ET.AL. (66)",0,1,1,G,L,"0-NN-1(N,TOT),,SIG","NEUTRON TOTAL CROSS SECTIONS FOR NEUTRONS, PRO...",1966,19800804,(1USAHRV),"N,TOT",TOT,1.0,Other,8071.31713,0.00046,0.0,0.0,782.347,0.0,1.008665e+06,0.00049,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0005,0.0,-0.0,2224.566,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,6257.229,0.0,763.755,20577.6194,0.0,1.0
3,1,G,3,1,119600000.0,1196000.0,0.0264,0.001403,NaN,NaN,NaN,NaN,L,"D.F.MEASDAY,ET.AL. (66)",0,1,1,G,L,"0-NN-1(N,TOT),,SIG","NEUTRON TOTAL CROSS SECTIONS FOR NEUTRONS, PRO...",1966,19800804,(1USAHRV),"N,TOT",TOT,1.0,Other,8071.31713,0.00046,0.0,0.0,782.347,0.0,1.008665e+06,0.00049,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0005,0.0,-0.0,2224.566,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,6257.229,0.0,763.755,20577.6194,0.0,1.0
4,1,G,3,1,129400000.0,1294000.0,0.0256,0.001397,NaN,NaN,NaN,NaN,L,"D.F.MEASDAY,ET.AL. (66)",0,1,1,G,L,"0-NN-1(N,TOT),,SIG","NEUTRON TOTAL CROSS SECTIONS FOR NEUTRONS, PRO...",1966,19800804,(1USAHRV),"N,TOT",TOT,1.0,Other,8071.31713,0.00046,0.0,0.0,782.347,0.0,1.008665e+06,0.00049,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0005,0.0,-0.0,2224.566,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,6257.229,0.0,763.755,20577.6194,0.0,1.0

In [20]:
columns_drop = ["MF", "Cos/LO", "dCos/LO", "M_x", "M_y", "N"]
df = df.drop(columns=columns_drop)

In [21]:
df["O"].fillna(value="Other", inplace=True)
df["Title"].fillna(value="NT", inplace=True)
df["Neutrons"].fillna(value=10, inplace=True)
df["Mass_Number"].fillna(value=20, inplace=True)

In [22]:
df["Neutrons"] = df["Neutrons"].astype(int)
df["Mass_Number"] = df["Mass_Number"].astype(int)

In [23]:
df = df.fillna(value=0.0)
df = df.dropna(axis=0)
df.shape

In [27]:
df = df.rename(columns={"Z":"Protons", "Type":"Reaction_Notation", "EL":"Element", "O":"Origin"})

In [28]:
df = df.drop(columns=["Prj"])

In [29]:
df["Product_Meta_State"] = df["Product_Meta_State"].astype(str)
df["Product_Meta_State"] = df["Product_Meta_State"].replace(to_replace="?", value="G")

In [30]:
df["Energy"] = df["Energy"].replace(to_replace=0, value=np.nan)
df = df.dropna(axis=0, how='any', thresh=None, subset=["Energy"])

# Uncertainty Missing Values

The uncertainty is not given for every experiment. Missing values happen when they are not specified in the entries and are given in the respective paper, or are simply not given. In any case, it will be very tidius to go one by one finding uncertanties. For this, we take the mean of the current uncertanties and fill missing values using the mean uncertantity multiply times the energy values.

In [31]:
uncertainty_energy = (df["dEnergy"]/df["Energy"]).mean()

df["dEnergy2"] = df["Energy"] * uncertainty_energy
df["dEnergy"] = df["dEnergy"].replace(to_replace=0, value=np.nan)
df['dEnergy'] = df['dEnergy'].fillna(df['dEnergy2'])

    
df = df.drop(columns=["dEnergy2"])
df["Nuc_Radius_fm"] = 1.25 * np.power(df["Mass_Number"], 1/3)
df["Neut_Nuc_Rad_Ratio"] = 1.25 / df["Nuc_Radius_fm"]

In [32]:
df.to_csv("working_xs_v1.csv", index=False)